### ISSUE TITLE
proxy page

### ISSUE THREAD

**Issue by ebonan** [Esri/WMSMultiDimensionalEsriViewer#4]
first of all many compliments for the webapp,it's realy nice !
we downloaded and deployed the app on our server and  tried to use it loading our netcdf mws.
everytime we get an error message "failed".
looking at the doc it seems that we need a proxy page.
is there any  example of proxy page implementation to use ? 
enrico

**Comment by kevinsigwart** [comment]
I just added an example proxy that can be used with IIS.  For more information and examples, please refer to the documentation here https://developers.arcgis.com/javascript/jshelp/ags_proxy.html

Kevin

**Comment by ebonan** [comment]
great!!! next week we'll try . 
Enrico
